apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    service-monitor: "main"
  name: prometheus-operator
  namespace: monitoring
spec:
  endpoints:
    - honorLabels: true
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator