name: Deploy Infrastructure
on:
  push:
    branches:
      - development
      - production
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com

    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch names
        uses: tj-actions/branch-names@v6
        id: branch-name

      - name: Environments Setup
        run: |
          echo "CURRENT_BRANCH=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV

      # ------------------------------------------------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: azure/setup-kubectl@v3
        id: install
      # ------------------------------------------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      # ------------------------------------------------------------------------------------
      - name: Terraform Init
        run: |
          terraform init --var-file variables/${{env.CURRENT_BRANCH}}.tfvars  -backend-config="profile="
          terraform workspace new ${{env.CURRENT_BRANCH}} || terraform workspace select ${{env.CURRENT_BRANCH}}

#      - name: Terraform Refresh
#        run: |
#          terraform refresh --var-file variables/${{env.CURRENT_BRANCH}}.tfvars -var="profile="

      # ------------------------------------------------------------------------------------
      - name: Terraform Format
        run: terraform fmt
      # ------------------------------------------------------------------------------------
      - name: Terraform Plan
        run: terraform plan --var-file variables/${{env.CURRENT_BRANCH}}.tfvars -var="profile="
      # ------------------------------------------------------------------------------------
      - name: Terraform Apply
        run: terraform apply --var-file variables/$CURRENT_BRANCH.tfvars -var="profile="  -auto-approve
